import { IMovie } from "../../services/Types";

export const MoviesData: IMovie[] = [
  {
    id: 753342,
    title: "Napoleon",
    poster_path: "https://image.tmdb.org/t/p/w500/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg",
    overview: "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
    year: "2023",
    genre_ids: [36, 10752, 18],
    language: "en",
  },
  {
    id: 906126,
    title: "Society of the Snow",
    poster_path: "https://image.tmdb.org/t/p/w500/2e853FDVSIso600RqAMunPxiZjq.jpg",
    overview: "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
    year: "2023",
    genre_ids: [18, 36],
    language: "es",
  },
  {
    id: 955916,
    title: "Lift",
    poster_path: "https://image.tmdb.org/t/p/w500/46sp1Z9b2PPTgCMyA87g9aTLUXi.jpg",
    overview: "An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.",
    year: "2024",
    genre_ids: [28, 35, 80],
    language: "en",
  },
  {
    id: 899445,
    title: "Deep Fear",
    poster_path: "https://image.tmdb.org/t/p/w500/ruujFw7J0Nd3BSjbN3QODym82Qs.jpg",
    overview:
      "A solo trip aboard a yacht takes a terrifying turn when a woman encounters three drug traffickers clinging to the shattered remains of a boat. They soon force her to dive into shark-infested waters to retrieve kilos of cocaine from the sunken wreck.",
    year: "2023",
    genre_ids: [28, 9648, 53, 27],
    language: "en",
  },
  {
    id: 572802,
    title: "Aquaman and the Lost Kingdom",
    poster_path: "https://image.tmdb.org/t/p/w500/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg",
    overview:
      "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    year: "2023",
    genre_ids: [28, 12, 14],
    language: "en",
  },
  {
    id: 1155089,
    title: "Justice League: Crisis on Infinite Earths Part One",
    poster_path: "https://image.tmdb.org/t/p/w500/zR6C66EDklgTPLHRSmmMt5878MR.jpg",
    overview:
      "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!",
    year: "2024",
    genre_ids: [16, 878, 28],
    language: "en",
  },
  {
    id: 866398,
    title: "The Beekeeper",
    poster_path: "https://image.tmdb.org/t/p/w500/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
    overview: "One man’s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    year: "2024",
    genre_ids: [28, 53],
    language: "en",
  },
  {
    id: 609681,
    title: "The Marvels",
    poster_path: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    overview:
      "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
    year: "2023",
    genre_ids: [878, 12, 28],
    language: "en",
  },
  {
    id: 927107,
    title: "The Bricklayer",
    poster_path: "https://image.tmdb.org/t/p/w500/pwOQ9lqLX1OgsJRSybS662wMcu8.jpg",
    overview:
      "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
    year: "2024",
    genre_ids: [28, 53],
    language: "en",
  },
  {
    id: 787699,
    title: "Wonka",
    poster_path: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    overview: "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    year: "2023",
    genre_ids: [35, 10751, 14],
    language: "en",
  },
  {
    id: 918692,
    title: "Granit",
    poster_path: "https://image.tmdb.org/t/p/w500/zLJn4U2qlWIzlFP5SsyFJUDQjfs.jpg",
    overview: 'Mozambique requests from Russia is being helped in the fight against militants of the "Islamic State" and a special group led by a commander with the call sign Granit is coming to the country.',
    year: "2021",
    genre_ids: [28, 10752],
    language: "ru",
  },
  {
    id: 901362,
    title: "Trolls Band Together",
    poster_path: "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    year: "2023",
    genre_ids: [16, 10751, 10402, 14, 35],
    language: "en",
  },
  {
    id: 1075794,
    title: "Leo",
    poster_path: "https://image.tmdb.org/t/p/w500/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    overview:
      "Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.",
    year: "2023",
    genre_ids: [16, 35, 10751],
    language: "en",
  },
  {
    id: 491854,
    title: "Foxtrot Six",
    poster_path: "https://image.tmdb.org/t/p/w500/o7c8FKCZFIrLKrZSzgqufvNo4mr.jpg",
    overview:
      "Escalating climate change is turning the world economy upside down. With crops dying and food price spiking, FOOD has replaced oil as the world's most valuable commodity.  Among the very few lands still left fertile, Indonesia is quickly rising as the next economic superpower, when its government is suddenly and ruthlessly overtaken by a popular rogue political party.  In just three days, six former Marines must work together, find their long-lost brotherhood, stop a nationwide government- sanctioned genocide, and save millions of lives, for one last shot at redemption. Or die trying.",
    year: "2019",
    genre_ids: [28, 878],
    language: "en",
  },
  {
    id: 872585,
    title: "Oppenheimer",
    poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    year: "2023",
    genre_ids: [18, 36],
    language: "en",
  },
  {
    id: 695721,
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    poster_path: "https://image.tmdb.org/t/p/w500/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
    overview: "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
    year: "2023",
    genre_ids: [18, 878, 28],
    language: "en",
  },
  {
    id: 502356,
    title: "The Super Mario Bros. Movie",
    poster_path: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    year: "2023",
    genre_ids: [16, 10751, 12, 14, 35],
    language: "en",
  },
  {
    id: 79026,
    title: "El padrino: The Latin Godfather",
    poster_path: "https://image.tmdb.org/t/p/w500/10J7EQ8WvMYku8lcZrLewV2Ko4I.jpg",
    overview:
      "In the streets of East Los Angeles, Manny is a formidable drug dealer. Impressed by his extravagant lifestyle and prowess, his young son, Kilo, yearns to follow in his footsteps. Kilo resolves to learn how to prosper in the drug world, and his new life as a dealer begins. In a world where a man wants everything, he may end up with nothing.",
    year: "2004",
    genre_ids: [28, 80, 18],
    language: "en",
  },
  {
    id: 1029575,
    title: "The Family Plan",
    poster_path: "https://image.tmdb.org/t/p/w500/a6syn9qcU4a54Lmi3JoIr1XvhFU.jpg",
    overview: "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
    year: "2023",
    genre_ids: [28, 35],
    language: "en",
  },
  {
    id: 848326,
    title: "Rebel Moon - Part One: A Child of Fire",
    poster_path: "https://image.tmdb.org/t/p/w500/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg",
    overview:
      "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
    year: "2023",
    genre_ids: [878, 18, 28],
    language: "en",
  },
  {
    id: 843380,
    title: "Dead for a Dollar",
    poster_path: "https://image.tmdb.org/t/p/w500/1AnXfjxFqMsQmUPSvt9YxUJhfFw.jpg",
    overview:
      "In 1897, veteran bounty hunter Max Borlund is deep into Mexico where he encounters professional gambler and outlaw Joe Cribbens — a sworn enemy he sent to prison years before. Max is on a mission to find and return Rachel Kidd, the wife of a wealthy businessman, who as the story is told to Max, has been abducted by Buffalo Soldier Elijah Jones. Max is ultimately faced with a showdown to save honor.",
    year: "2022",
    genre_ids: [37, 53, 28],
    language: "en",
  },
  {
    id: 1214314,
    title: "One More Shot",
    poster_path: "https://image.tmdb.org/t/p/w500/nQ1BQg4yMdlYSHvHZgwladzy7EF.jpg",
    overview:
      "Following the attack on the black site in Poland, Navy SEAL Jake Harris is ordered to escort terrorist suspect Amin Mansur to Washington D.C. for interrogation. Before the prisoner transfer process is complete, though, the airport is attacked by a group of heavily armed, well-trained mercenaries.",
    year: "2024",
    genre_ids: [28, 53],
    language: "en",
  },
  {
    id: 385687,
    title: "Fast X",
    poster_path: "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    year: "2023",
    genre_ids: [28, 80, 53],
    language: "en",
  },
  {
    id: 508883,
    title: "The Boy and the Heron",
    poster_path: "https://image.tmdb.org/t/p/w500/jDQPkgzerGophKRRn7MKm071vCU.jpg",
    overview:
      "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    year: "2023",
    genre_ids: [16, 12, 14],
    language: "ja",
  },
  {
    id: 466420,
    title: "Killers of the Flower Moon",
    poster_path: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    overview: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
    year: "2023",
    genre_ids: [80, 18, 36],
    language: "en",
  },
  {
    id: 816741,
    title: "Grey Eyes",
    poster_path: "https://image.tmdb.org/t/p/w500/5InVYa7CcbGioPvQ6ig4Lz4iLlR.jpg",
    overview:
      "In a post-apocalyptic future, mankind is color blind. A brilliant scientist suddenly dies, leaving his precious briefcase-filled with a highly-addictive synthetic drug that allows people to see colors again-to Ana, a mere 12-year-old girl. Possession of the briefcase makes her the target of a doctor with wicked plans for the drug, and her only hope to escape his pursuit relies on the aid of the dead scientist's two devoted bodyguards. Together, their epic, perilous journey pivots on a tremendous secret: Ana herself could be the key to salvaging a world in ruins.",
    year: "2018",
    genre_ids: [28, 878],
    language: "es",
  },
  {
    id: 346698,
    title: "Barbie",
    poster_path: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    year: "2023",
    genre_ids: [35, 12, 14],
    language: "en",
  },
  {
    id: 520758,
    title: "Chicken Run: Dawn of the Nugget",
    poster_path: "https://image.tmdb.org/t/p/w500/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg",
    overview: "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
    year: "2023",
    genre_ids: [16, 12, 35, 10751],
    language: "en",
  },
  {
    id: 786573,
    title: "HellKat",
    poster_path: "https://image.tmdb.org/t/p/w500/sNUQVeU78lVomwC7bR8SyCRnjdg.jpg",
    overview: "A fallen MMA fighter must win a netherworld no-holds-barred death tournament against man, beast and demon to save her soul.",
    year: "2021",
    genre_ids: [28, 53, 27],
    language: "en",
  },
  {
    id: 940721,
    title: "Godzilla Minus One",
    poster_path: "https://image.tmdb.org/t/p/w500/bWhNxtPlMsGBbM4ybg9C6nWnxBV.jpg",
    overview: "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
    year: "2023",
    genre_ids: [878, 27, 28],
    language: "ja",
  },
  {
    id: 1133602,
    title: "Bad Lands",
    poster_path: "https://image.tmdb.org/t/p/w500/o8CB6o7ouYPgi8WIXKAR4Hgz3ud.jpg",
    overview: "A grifter and her loose-cannon brother get their hands on a massive amount of money, but their ill-gotten gains puts a huge target on their back.",
    year: "2023",
    genre_ids: [28, 80],
    language: "ja",
  },
  {
    id: 928833,
    title: "Craig Before the Creek",
    poster_path: "https://image.tmdb.org/t/p/w500/4gDNAsYbCOP3z4xyM0IhbPl5Rq3.jpg",
    overview:
      "Before he was Craig of the Creek, he was just Craig — a new kid in a new town. All Craig wants is to go back to his old friends at his old home. But when he learns that the nearby creek is hiding a lost treasure that could make his wish come true, Craig sets off on a journey to find it — navigating the perilous suburban wilderness, forging new friendships, all while being pursued by a fearsome band of pirates who are bent on destroying the Creek itself.",
    year: "2023",
    genre_ids: [16, 10751, 10770, 12, 35, 14],
    language: "en",
  },
  {
    id: 976573,
    title: "Elemental",
    poster_path: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    overview: "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
    year: "2023",
    genre_ids: [16, 35, 10751, 14, 10749, 12],
    language: "en",
  },
  {
    id: 299054,
    title: "Expend4bles",
    poster_path: "https://image.tmdb.org/t/p/w500/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
    overview:
      "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
    year: "2023",
    genre_ids: [28, 12, 53],
    language: "en",
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    poster_path: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    year: "2023",
    genre_ids: [16, 28, 12, 878],
    language: "en",
  },
  {
    id: 940551,
    title: "Migration",
    poster_path: "https://image.tmdb.org/t/p/w500/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    overview: "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    year: "2023",
    genre_ids: [16, 12, 35, 10751],
    language: "en",
  },
  {
    id: 930564,
    title: "Saltburn",
    poster_path: "https://image.tmdb.org/t/p/w500/qjhahNLSZ705B5JP92YMEYPocPz.jpg",
    overview:
      "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton, who invites him to Saltburn, his eccentric family's sprawling estate, for a summer never to be forgotten.",
    year: "2023",
    genre_ids: [18, 35, 53],
    language: "en",
  },
  {
    id: 772,
    title: "Home Alone 2: Lost in New York",
    poster_path: "https://image.tmdb.org/t/p/w500/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg",
    overview:
      "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas Eve.",
    year: "1992",
    genre_ids: [35, 10751, 12],
    language: "en",
  },
  {
    id: 447362,
    title: "Life in a Year",
    poster_path: "https://image.tmdb.org/t/p/w500/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
    overview: "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
    year: "2020",
    genre_ids: [18, 10749],
    language: "en",
  },
  {
    id: 507089,
    title: "Five Nights at Freddy's",
    poster_path: "https://image.tmdb.org/t/p/w500/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
    overview:
      "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
    year: "2023",
    genre_ids: [27, 9648],
    language: "en",
  },
];

export const genreList = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
  {
    id: 10759,
    name: "Action & Adventure",
  },
  {
    id: 10762,
    name: "Kids",
  },
  {
    id: 10763,
    name: "News",
  },
  {
    id: 10764,
    name: "Reality",
  },
  {
    id: 10765,
    name: "Sci-Fi & Fantasy",
  },
  {
    id: 10766,
    name: "Soap",
  },
  {
    id: 10767,
    name: "Talk",
  },
  {
    id: 10768,
    name: "War & Politics",
  },
];

export const genres: { [key: number]: string } = {
  12: "Adventure",
  14: "Fantasy",
  16: "Animation",
  18: "Drama",
  27: "Horror",
  28: "Action",
  35: "Comedy",
  36: "History",
  37: "Western",
  53: "Thriller",
  80: "Crime",
  99: "Documentary",
  878: "Science Fiction",
  9648: "Mystery",
  10402: "Music",
  10749: "Romance",
  10751: "Family",
  10752: "War",
  10759: "Action & Adventure",
  10762: "Kids",
  10763: "News",
  10764: "Reality",
  10765: "Sci-Fi & Fantasy",
  10766: "Soap",
  10767: "Talk",
  10768: "War & Politics",
  10770: "TV Movie",
};

// export const MovieFilters = ["Popular", "Now Playing", "Upcoming"];
// export const TvShowFilters = ["On The Air", "Popular", "Top Rated"];
export const TMDB_NULL_URL = "https://image.tmdb.org/t/p/w500null";
export const NO_IMG_URL = "https://www.rockettstgeorge.co.uk/cdn/shop/products/no_selection_46a68bcd-4f07-453a-bd6f-b50da3d486d0.jpg?v=1683702587";

export const frozenMovieSearchRes = [
  {
    id: 109445,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    overview:
      "Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She's accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.",
    year: "2013",
    genre_ids: [16, 10751, 12, 14],
    language: "en",
  },
  {
    id: 44363,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500/kEiMX42a35S4blAw4KrQe3U5zNc.jpg",
    overview: "When three skiers find themselves stranded on a chair lift at a New England ski resort that has closed for the next week, they are forced to make life or death choices that prove to be more perilous than staying put and freezing to death.",
    year: "2010",
    genre_ids: [53],
    language: "en",
  },
  {
    id: 26041,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500/a6RlPQUerliQLkAieku5B8Loamk.jpg",
    overview:
      "It's two years since the mysterious disappearance of Kath Swarbrick's older sister Annie, but Kath remains haunted by a need to know what happened. When police investigations wind down, Kath continues the search herself. She gets nowhere until she steals some CCTV footage of her sister on her final day. Visiting the spot where Annie was filmed, Kath becomes convinced she has found a portal to another reality and from this portal Kath is trying to say something.",
    year: "2005",
    genre_ids: [53],
    language: "en",
  },
  {
    id: 170986,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500/2GL9yZtrgbYKCeKBc3TF9gGfZpX.jpg",
    overview:
      "This is a touching and somber journey of Lasya, who lives with her father Karma and younger brother Chomo in a remote village in the Himalayas. Pristine snow capped mountains surround their tiny hamlet and barren harsh land stretches for miles into nowhere. One day the army moves in, settles a hundred yards across their doorstep. The last bit of comfort the family draws from their familiar surroundings changes into a harsh ceaseless irreversible conflict. The film depicts the life of this family whose dream like existence is interrupted by inevitable odds, one after the other.",
    year: "2007",
    genre_ids: [18, 27],
    language: "hi",
  },
  {
    id: 950554,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500null",
    overview: "A film by Adonia Bouchehri.",
    year: "NaN",
    genre_ids: [],
    language: "en",
  },
  {
    id: 573171,
    title: "A Frozen Rooster",
    poster_path: "https://image.tmdb.org/t/p/w500/Qotf3QgDqUZEW6pfQl2BPxZCRn.jpg",
    overview:
      "Follow the adventures of Toto and his family, who will have to travel to the South Pole to fulfill their promise to return a polar bear and some Spanish penguins to their home. In order to fulfill the promise, they will have to overcome some obstacles that will teach them how important teamwork is.",
    year: "2022",
    genre_ids: [16, 12, 35, 10751],
    language: "es",
  },
  {
    id: 330457,
    title: "Frozen II",
    poster_path: "https://image.tmdb.org/t/p/w500/mINJaa34MtknCYl5AjtNJzWj8cD.jpg",
    overview: "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
    year: "2019",
    genre_ids: [10751, 16, 12, 35, 14],
    language: "en",
  },
  {
    id: 17903,
    title: "A Frozen Flower",
    poster_path: "https://image.tmdb.org/t/p/w500/jvGmbNUh0eq9ShQmMSof0DXXHWY.jpg",
    overview: "A historical drama set in the Koryo dynasty and focused on the relationship between a king and his bodyguard.",
    year: "2008",
    genre_ids: [18],
    language: "ko",
  },
  {
    id: 566451,
    title: "Re:ZERO -Starting Life in Another World- The Frozen Bond",
    poster_path: "https://image.tmdb.org/t/p/w500/ca2ZsUa4Qeik2IwlXFzV51hdxh0.jpg",
    overview:
      "Covered in ice and snow, Elior Forest is the home to dangerous magical beasts and 50 elves frozen in ice. One day, the great spirit Puck helps a young girl break out of her ice prison. Her name is Emilia, a half-elf born with silver hair, long ears, and amethyst eyes—features that resemble the evil Witch who destroyed half the world long ago.  Shunned by society because of her appearance, Emilia dwells in the forest with Puck as her sole companion and family. Burdened with a sin of destruction she does not remember committing, she spends her days trying to find a way to help her frozen kin. But when the great spirit Melakuera, the Arbitrator of the world, finds Emilia, her right to stay alive is brought into question. Will the bonds of ice she formed with Puck prove to be the warm thread that defies fate?",
    year: "2019",
    genre_ids: [16, 18, 53, 14],
    language: "ja",
  },
  {
    id: 326359,
    title: "Frozen Fever",
    poster_path: "https://image.tmdb.org/t/p/w500/mPrDJ7puYzPLG5kPM96iNszF2sM.jpg",
    overview: "On Anna's birthday, Elsa and Kristoff are determined to give her the best celebration ever, but Elsa's icy powers may put more than just the party at risk.",
    year: "2015",
    genre_ids: [16, 10751, 12, 35],
    language: "en",
  },
  {
    id: 967847,
    title: "Ghostbusters: Frozen Empire",
    poster_path: "https://image.tmdb.org/t/p/w500/mLk6vqLP3fgplHYhEZzqODiGdEG.jpg",
    overview:
      "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
    year: "2024",
    genre_ids: [14, 12, 35],
    language: "en",
  },
  {
    id: 431562,
    title: "LEGO Frozen Northern Lights",
    poster_path: "https://image.tmdb.org/t/p/w500/jlk5MeGlNSiy773SWot9dGAQ2as.jpg",
    overview: "Elsa, Anna and friends search for the Northern Lights.",
    year: "2017",
    genre_ids: [16, 10751],
    language: "en",
  },
  {
    id: 460793,
    title: "Olaf's Frozen Adventure",
    poster_path: "https://image.tmdb.org/t/p/w500/As8WTtxXs9e3cBit3ztTf7zoRmm.jpg",
    overview: "Olaf is on a mission to harness the best holiday traditions for Anna, Elsa, and Kristoff.",
    year: "2017",
    genre_ids: [16, 10751, 12, 35, 14],
    language: "en",
  },
  {
    id: 95174,
    title: "Frozen",
    poster_path: "https://image.tmdb.org/t/p/w500/etDRhc599Q2JCaUu8k7ei2hqmgZ.jpg",
    overview:
      "A young 20-year-old-woman named Wing (Lan Wei) visits her grandfather's laboratory in Hong Kong. By accident, Wing opens a chamber and resurrects a woman about her age. Wing then discovers the woman awaken is her mother Gigi (Janice Man), who was cryogenically frozen shortly after becoming involved in a fatal car accident some 20 years ago. Gigi, on the other hand, must also come to grips with her daughter being the same age as her and also her favorite actor Leslie Cheung having long passed away.  The newly acquainted mother and daughter duo then set out to find Gigi's boyfriend Kit (Aarif Lee) who is also Wing's biological father. When they find Kit, they learn that he's not the same man as he was twenty years ago and, in fact, a middle-aged homeless man who lives under a bridge ...",
    year: "2010",
    genre_ids: [14, 53, 10749],
    language: "cn",
  },
  {
    id: 18279,
    title: "Frozen Land",
    poster_path: "https://image.tmdb.org/t/p/w500/d9LQMkkD7TPB0r7HGqjKRtvypFU.jpg",
    overview:
      "When a schoolteacher is sacked, he projects his bad mood at his troubled teenage son. The son, in turn, buys a CD player from a pawnshop with counterfeit money. This starts a chain reaction of misery as every victim projects his problems on to another person.",
    year: "2005",
    genre_ids: [18],
    language: "fi",
  },
  {
    id: 199373,
    title: "The Frozen Ground",
    poster_path: "https://image.tmdb.org/t/p/w500/hHDj1h3lJvYd9Cervoswz9crhWg.jpg",
    overview: "An Alaska State Trooper partners with a young woman who escaped the clutches of serial killer Robert Hansen to bring the murderer to justice. Based on actual events.",
    year: "2013",
    genre_ids: [53, 80],
    language: "en",
  },
  {
    id: 15303,
    title: "Frozen Stiff",
    poster_path: "https://image.tmdb.org/t/p/w500/hXbGz9XJy9HqxdJyursXIv4669x.jpg",
    overview:
      "The basic plot revolves around drug dealer Limeni and two men, Lemi and Kiza, who are trying to transport their dead grandfather for burial, until their car breaks down and they end up struggling to get him home onboard a train. This is when these two plots intersect and all hell breaks loose.",
    year: "2002",
    genre_ids: [18, 35],
    language: "sr",
  },
  {
    id: 85434,
    title: "Frozen Silence",
    poster_path: "https://image.tmdb.org/t/p/w500/rJEC6CoYifZYNnHNvIjtIS36Fgy.jpg",
    overview: "Russian front, winter 1943. Soldier Arturo Andrade and Sergeant Fernando Espinosa are commissioned to investigate a mysterious murder while the Spanish Blue Division of the German Army endures the fierce counterattack of the Red Army.",
    year: "2012",
    genre_ids: [10752, 9648, 18],
    language: "es",
  },
  {
    id: 1024604,
    title: "Frozen 3",
    poster_path: "https://image.tmdb.org/t/p/w500/8eUfD6fzNWWyuwUYxeSI3grxpy0.jpg",
    overview: "Third installment to the Frozen animated movie franchise. Plot TBA.",
    year: "NaN",
    genre_ids: [16, 10751, 14],
    language: "en",
  },
  {
    id: 184587,
    title: "Frozen Angels",
    poster_path: "https://image.tmdb.org/t/p/w500/m8EGV4LqtSrtnpp7dfddx3oHXcX.jpg",
    overview: "A scientific and social exploration of the future of human reproductive technology.  In vitro fertilization, sperm banks' potential repercussions and the ethics of genetically engineering babies are among the issues examined.",
    year: "2005",
    genre_ids: [99],
    language: "en",
  },
];

export const frozenTvSeachRes = [
  {
    id: 236616,
    title: "黑土无言",
    poster_path: "https://image.tmdb.org/t/p/w500/rE1pPrUop9zdGTnaK72DX1lJlxW.jpg",
    overview:
      "Guan Yu, who was a soldier, has a meticulous mind, rigorous style, and extremely hard physical and mental quality. He has solved numerous major and small cases. From a simple and fierce little white criminal policeman, he has grown all the way to a wise and experienced Lanhe County Criminal Police Team Captain. Guan Yu's physical condition went from bad to worse after being promoted to captain of the criminal police. After the 1223 major case, Guan Yu was faced with danger. Under the pressure of time, pressure from superiors, and the loss of relatives and comrades in arms, the black hand of evil is still hidden under the glacier. In the face of this case with many intertwined and implicated cases, can Guan Yu hold high the light of justice and the fire of hope in his hands?",
    year: "2024",
    genre_ids: [9648, 80],
    language: "zh",
  },
  {
    id: 223712,
    title: "Мерзлая земля",
    poster_path: "https://image.tmdb.org/t/p/w500/xR3tAGpZAVk7J5qQI5O3CZcQ6sj.jpg",
    overview:
      "Taxi driver Larisa Aidarova from a small seaside town is preparing for the wedding with her beloved Maksim, with whom she has been working and living together for more than a year. But all plans collapse when Maksim is detained on suspicion of murder.",
    year: "2023",
    genre_ids: [18, 9648],
    language: "ru",
  },
  {
    id: 215467,
    title: "Замёрзшие",
    poster_path: "https://image.tmdb.org/t/p/w500/hnczyTV7OI8Ajk4AF0MTNl3QpA9.jpg",
    overview:
      "On a snow-covered highway near the northern town of Kostomuksha, police find the frozen corpse of a woman in a frozen car. The victim is the wife of investigator Evgeniy Rudin. The rage that has taken possession of the hero leads him along the path of senseless cruelty, the victims of which can be both innocent people and those close to Rudin. Evgeniy finds unexpected support in the face of a strange boy Mitya. Meanwhile, the killings continue.",
    year: "2022",
    genre_ids: [9648],
    language: "ru",
  },
  {
    id: 26411,
    title: "凍りつく夏",
    poster_path: "https://image.tmdb.org/t/p/w500/rA5eE0JSMEI2NKlXG4yfe50EjiY.jpg",
    overview:
      "The Oikawa children are still coming to terms with the death of their mother and the addition of a stepmother. The head of the family takes out his frustration on the children, inflicting mental and physical wounds, while the children’s lives outside the home reflect their abuse as they get into everything from street violence to teenage companion services. A sharp lawyer and new stepmother to the children attempts to forge a stable family, but as she does so the mystery behind her predecessor’s death slowly becomes chillingly clear to her.",
    year: "1998",
    genre_ids: [18],
    language: "ja",
  },
  {
    id: 79281,
    title: "빙구",
    poster_path: "https://image.tmdb.org/t/p/w500/glfI2qdo8V80YFkeWiJYZmvZgSC.jpg",
    overview:
      "After being frozen for 33 years, Man Soo finds himself awake in a cold body but he has enormous love in his heart. He meets Ha Da, who has turned into a cold-hearted human being after living in the city. Now that Man Soo is awake from his slumber, he embarks on a search for his long-lost love through time while Ha Da, whom he encountered, is discovering warmth in her heart.Will either of them find love? This TV show aims to weave a beautiful story of romance to uplift viewers who are dealing with a depressed economy and dim job prospects in a harsh society of today.\n\n(Source: MBC)",
    year: "2017",
    genre_ids: [18, 10765],
    language: "ko",
  },
  {
    id: 103465,
    title: "Into the Unknown: Making Frozen II",
    poster_path: "https://image.tmdb.org/t/p/w500/UcbjmltlDTxoZvTSPbQtUBeZEo.jpg",
    overview:
      "The team behind Frozen II open their doors to cameras for a six-part documentary series to reveal the hard work, heart, and collaboration it takes to create one of the most highly-anticipated films in Walt Disney Animation Studios’ near-century of moviemaking. Cameras were there to capture an eye-opening - and at times jaw-dropping - view of the challenges and the breakthroughs, the artistry, creativity and the complexity of creating the #1 animated feature of all time.",
    year: "2020",
    genre_ids: [99],
    language: "en",
  },
  {
    id: 69488,
    title: "Glacé",
    poster_path: "https://image.tmdb.org/t/p/w500/kUzTRUCfu3RuNqmb6KEVqNFuIfv.jpg",
    overview:
      "A horrific discovery in a small town nestled high in the French Pyrenees begins to unravel a dark mystery that has been hidden for years. On an unforgiving winter morning, a group of workers discover the headless body of a horse, hanging suspended from the edge of a frozen cliff. Commandant Martin Servaz starts investigating and soon discovers a dark story of madness and revenge.",
    year: "2017",
    genre_ids: [18],
    language: "fr",
  },
  {
    id: 116155,
    title: "Frozen Planet II",
    poster_path: "https://image.tmdb.org/t/p/w500/p3hSdvuPfx7AXgOk7Ut1Spin6FJ.jpg",
    overview:
      "Ten years on from the original Frozen Planet, this documentary series takes audiences back to the wildernesses of the Arctic and Antarctica and tells the complete story of the entire frozen quarter of our planet that’s locked in ice and blanketed in snow.",
    year: "2022",
    genre_ids: [99],
    language: "en",
  },
  {
    id: 8724,
    title: "Frozen Planet",
    poster_path: "https://image.tmdb.org/t/p/w500/rDlNybzqSf2W8sI5ht0fXWpSHWJ.jpg",
    overview: "David Attenborough travels to the end of the earth, taking viewers on an extraordinary journey across the polar regions of our planet.",
    year: "2011",
    genre_ids: [99],
    language: "en",
  },
  {
    id: 63882,
    title: "Curse of the Frozen Gold",
    poster_path: "https://image.tmdb.org/t/p/w500/9TUWjGIB7tpW0U4b3wVsIkS6P4g.jpg",
    overview: "In the treacherous wilds of British Columbia, six prospectors pursue a cursed cache of gold worth billions. With just a few short weeks to complete their mission, they'll combine their skills to find the fortune, or fall victim to the curse.",
    year: "2015",
    genre_ids: [10764],
    language: "en",
  },
  {
    id: 113345,
    title: "قلب یخی",
    poster_path: "https://image.tmdb.org/t/p/w500/3OwrA9wBZdbghkHsuDj1aXLg7Yq.jpg",
    overview: "",
    year: "2010",
    genre_ids: [18],
    language: "fa",
  },
  {
    id: 76772,
    title: "Frusna Vägar",
    poster_path: "https://image.tmdb.org/t/p/w500/aLgNiCrePWrz60wCLqEH8vwVeO6.jpg",
    overview:
      "Follow along to a sparkling Sweden, up in the North, where snow and ice is an every day thing for salvager's and snow clearer's, but not comfortable for big city dwellers during their temporary visits. Follow the heroes that transforms the northern vastness to travel-able areas.",
    year: "2018",
    genre_ids: [99, 10764],
    language: "sv",
  },
  {
    id: 116357,
    title: "Frozen in Time",
    poster_path: "https://image.tmdb.org/t/p/w500/bXqYnhAotZ4oaMShlCdFLIs5urV.jpg",
    overview: "Maureen McCormick and designer Dan Vickery overhaul homes that are stuck in a design time warp.",
    year: "2021",
    genre_ids: [10764],
    language: "en",
  },
  {
    id: 73051,
    title: "Der kalte Himmel",
    poster_path: "https://image.tmdb.org/t/p/w500/mECfjl5V4IVwD5iIfEg3CH2UEFw.jpg",
    overview:
      "Fighting against the prejudices of late 1960s Germany, a mother will stop at nothing to find her son a proper psychiatric diagnosis. To society, he is a problem child; to his mother, he is gifted. Doctor Zhivago meets The A Word... an exquisite, arresting tale of love and hope.",
    year: "2011",
    genre_ids: [18],
    language: "de",
  },
  {
    id: 130228,
    title: "Debi Marshall Investigates: Frozen Lies",
    poster_path: "https://image.tmdb.org/t/p/w500/su27szZWFjX4KYjIoAO8hEIhsyV.jpg",
    overview: "Investigative crime journalist Debi Marshall explores one of Australia's most sensational murders – the case of the Lawyer in the Freezer.",
    year: "2019",
    genre_ids: [99, 80],
    language: "en",
  },
  {
    id: 113598,
    title: "Мёрзлая земля",
    poster_path: "https://image.tmdb.org/t/p/w500null",
    overview: "",
    year: "NaN",
    genre_ids: [18, 80, 9648],
    language: "ru",
  },
  {
    id: 224265,
    title: "Ice Age: A Frozen World",
    poster_path: "https://image.tmdb.org/t/p/w500/vSA2LgctXoskj9fdslivPizXhBU.jpg",
    overview: "A gripping journey through time, with a mixture of on location pieces, breathtaking Virtual Studio production and expert interviews. It will unravel the hidden secrets of the Ice Age and how it created the world we now live in.",
    year: "2023",
    genre_ids: [99],
    language: "en",
  },
  {
    id: 237992,
    title: "Frozen in Time: Flashback",
    poster_path: "https://image.tmdb.org/t/p/w500/j0aM1VCNmKcxraiyi1IHe9dCfcB.jpg",
    overview: "Interior designer Dan Vickery and The Brady Bunch's Maureen McCormick revisit some of their favourite overhauls of homes stuck in a time warp from other designers they love.",
    year: "2021",
    genre_ids: [99, 10764, 10751],
    language: "en",
  },
  {
    id: 212928,
    title: "Ancient Earth: Dinosaurs of the Frozen Continent",
    poster_path: "https://image.tmdb.org/t/p/w500/rhX3pKTCkHzvy0rDFvCtWPCKki.jpg",
    overview:
      "Deep under Antarctica’s blanket of ice lies traces of a lost world of Dinosaurs and pre-historic creatures. Great forests once covered the now frozen Antarctic continent; gargantuan titanosaurs roamed its valleys, and proto-mammals darted through the undergrowth. It was also home to the largest carnivore of its day, the Cryolophosaurus – Antarctica’s T-Rex.",
    year: "2022",
    genre_ids: [99],
    language: "en",
  },
  {
    id: 62041,
    title: "Alaska: Earth's Frozen Kingdom",
    poster_path: "https://image.tmdb.org/t/p/w500/w2WXnM9xRMHt57ls5gH1PeglUyV.jpg",
    overview: "Three-part series that looks at a year in Alaska, revealing the stories of pioneering Alaskans, both animal and human, as they battle the elements and reap the benefits of nature's seasonal gold rush.",
    year: "2015",
    genre_ids: [99],
    language: "en",
  },
];

export const frozenPostsSearchRes = [
  {
    _id: "65b282ea689532aa2ddaca7f",
    ownerId: "65b282ce689532aa2ddaca77",
    ownerName: "Test test",
    ownerImageUrl: "me.jpg",
    text: "Love it!",
    rating: 5,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:48:58.243Z",
  },
  {
    _id: "65b282ff689532aa2ddaca82",
    ownerId: "65b282ce689532aa2ddaca77",
    ownerName: "Test test",
    ownerImageUrl: "me.jpg",
    text: "Great movie!",
    rating: 5,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:49:19.175Z",
  },
  {
    _id: "65b283b4da2abe99fce3a03e",
    ownerId: "65b2831e689532aa2ddaca85",
    ownerName: "Aviv Cohen",
    ownerImageUrl: "https://lh3.googleusercontent.com/a/ACg8ocJKbiKtusYhGOf7LYTk1Qy2Ho62Wle8xMCVyBaIHREp=s96-c",
    text: "Good",
    rating: 3,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:52:20.693Z",
  },
  {
    _id: "65b283d0da2abe99fce3a041",
    ownerId: "65b2831e689532aa2ddaca85",
    ownerName: "Aviv Cohen",
    ownerImageUrl: "https://lh3.googleusercontent.com/a/ACg8ocJKbiKtusYhGOf7LYTk1Qy2Ho62Wle8xMCVyBaIHREp=s96-c",
    text: "This movie is great for the kids",
    rating: 4,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:52:48.394Z",
  },
  {
    _id: "65b282ea689532aa2ddaca7f",
    ownerId: "65b282ce689532aa2ddaca77",
    ownerName: "Test test",
    ownerImageUrl: "me.jpg",
    text: "Love it!",
    rating: 5,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:48:58.243Z",
  },
  {
    _id: "65b282ff689532aa2ddaca82",
    ownerId: "65b282ce689532aa2ddaca77",
    ownerName: "Test test",
    ownerImageUrl: "me.jpg",
    text: "Great movie!",
    rating: 5,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:49:19.175Z",
  },
  {
    _id: "65b283b4da2abe99fce3a03e",
    ownerId: "65b2831e689532aa2ddaca85",
    ownerName: "Aviv Cohen",
    ownerImageUrl: "https://lh3.googleusercontent.com/a/ACg8ocJKbiKtusYhGOf7LYTk1Qy2Ho62Wle8xMCVyBaIHREp=s96-c",
    text: "Good",
    rating: 3,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:52:20.693Z",
  },
  {
    _id: "65b283d0da2abe99fce3a041",
    ownerId: "65b2831e689532aa2ddaca85",
    ownerName: "Aviv Cohen",
    ownerImageUrl: "https://lh3.googleusercontent.com/a/ACg8ocJKbiKtusYhGOf7LYTk1Qy2Ho62Wle8xMCVyBaIHREp=s96-c",
    text: "This movie is great for the kids",
    rating: 4,
    imageUrl: "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
    tmdbId: "109445",
    tmdbTitle: "Frozen",
    tmdbImageUrl: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
    numOfComments: 0,
    createdAt: "2024-01-25T15:52:48.394Z",
  },
];

export const user = {
  _id: "65b2831e689532aa2ddaca85",
  fullName: "Aviv Cohen",
  email: "cohenaviv2@gmail.com",
  role: "user",
  password: "$2b$10$1oRf28bF5xNFSnFNkDOJ/OdTjcBMt8Ej/ZjID3Ot29BVKekAAcSOa",
  imageUrl: "https://lh3.googleusercontent.com/a/ACg8ocJKbiKtusYhGOf7LYTk1Qy2Ho62Wle8xMCVyBaIHREp=s96-c",
  googleId: "111355991550932592226",
  tokens: ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyODMxZTY4OTUzMmFhMmRkYWNhODUiLCJpYXQiOjE3MDYxOTc4ODV9.v-cWoBz3IysPdSynj06XZteV2l2QLwMPC7_KkezedGc"],
};

import * as FaIcons from "react-icons/fa6";
import styles from "../ButtonGroup/ButtonGroup.module.scss";
import { Button } from "../ButtonGroup/ButtonUtils";

export const MovieFilterButton: Button[] = [
  {
    label: "Popular",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaHeart />,
    path: "popular",
  },
  {
    label: "Now Playing",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaFilm />, // <FaClapperboard />
    path: "now-playing",
  },
  {
    label: "Upcoming",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaRegCalendarCheck />,
    path: "upcoming",
  },
];

export const TvShowFilterButton: Button[] = [
  {
    label: "On The Air",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaTowerCell />,
    path: "on-the-air",
  },
  {
    label: "Popular",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaHeart />,
    path: "popular",
  },
  {
    label: "Top Rated",
    onClick: () => null,
    cName: styles.filterBtn,
    icon: <FaIcons.FaRankingStar />,
    path: "top-rated",
  },
];

export const MovieGenreButtons: Button[] = [
  { label: "Action", onClick: () => null, cName: styles.genreBtn },
  { label: "Adventure", onClick: () => null, cName: styles.genreBtn },
  { label: "Animation", onClick: () => null, cName: styles.genreBtn },
  { label: "Comedy", onClick: () => null, cName: styles.genreBtn },
  { label: "Crime", onClick: () => null, cName: styles.genreBtn },
  { label: "Documentary", onClick: () => null, cName: styles.genreBtn },
  { label: "Drama", onClick: () => null, cName: styles.genreBtn },
  { label: "Family", onClick: () => null, cName: styles.genreBtn },
  { label: "Fantasy", onClick: () => null, cName: styles.genreBtn },
  { label: "History", onClick: () => null, cName: styles.genreBtn },
  { label: "Horror", onClick: () => null, cName: styles.genreBtn },
  { label: "Music", onClick: () => null, cName: styles.genreBtn },
  { label: "Mystery", onClick: () => null, cName: styles.genreBtn },
  { label: "Romance", onClick: () => null, cName: styles.genreBtn },
  { label: "Science Fiction", onClick: () => null, cName: styles.genreBtn },
  { label: "TV Movie", onClick: () => null, cName: styles.genreBtn },
  { label: "Thriller", onClick: () => null, cName: styles.genreBtn },
  { label: "War", onClick: () => null, cName: styles.genreBtn },
  { label: "Western", onClick: () => null, cName: styles.genreBtn },
];

export const TvShowGenreButtons: Button[] = [
  { label: "Action & Adventure", onClick: () => null, cName: styles.genreBtn },
  { label: "Animation", onClick: () => null, cName: styles.genreBtn },
  { label: "Comedy", onClick: () => null, cName: styles.genreBtn },
  { label: "Crime", onClick: () => null, cName: styles.genreBtn },
  { label: "Documentary", onClick: () => null, cName: styles.genreBtn },
  { label: "Drama", onClick: () => null, cName: styles.genreBtn },
  { label: "Family", onClick: () => null, cName: styles.genreBtn },
  { label: "Kids", onClick: () => null, cName: styles.genreBtn },
  { label: "Mystery", onClick: () => null, cName: styles.genreBtn },
  { label: "News", onClick: () => null, cName: styles.genreBtn },
  { label: "Reality", onClick: () => null, cName: styles.genreBtn },
  { label: "Sci-Fi & Fantasy", onClick: () => null, cName: styles.genreBtn },
  { label: "Soap", onClick: () => null, cName: styles.genreBtn },
  { label: "Talk", onClick: () => null, cName: styles.genreBtn },
  { label: "War & Politics", onClick: () => null, cName: styles.genreBtn },
  { label: "Western", onClick: () => null, cName: styles.genreBtn },
];
